### PR TITLE
build: update remote bazel toolchain version to 0.22

### PR DESCRIPTION
**Pull request by justbuchanan**
Borrowing from https://github.com/kythe/kythe/commit/54ba752c361ad66ee50b4f860260103d958b6805.

### CODE REVIEW

**Comment by shahms** [comment]
Approved too soon, looks like there's a bit more to be done.

**Comment by justbuchanan** [comment]
I updated a few things in the WORKSPACE based on the main kythe repo and it's still having some issues. I think it's the _local_lexyacc() macro in lexyacc.bzl of the kythe repo. It's trying to refer to `//tools/build_rules/lexyacc:lexyacc.bzl` (without an `@io_kythe` prefix) and it fails to find it in lang_proto.

**Comment by shahms** [comment]
> I updated a few things in the WORKSPACE based on the main kythe repo and it's still having some issues. I think it's the _local_lexyacc() macro in lexyacc.bzl of the kythe repo. It's trying to refer to `//tools/build_rules/lexyacc:lexyacc.bzl` (without an `@io_kythe` prefix) and it fails to find it in lang_proto.

Testing a fix for that now, will send shortly.

**Comment by justbuchanan** [comment]
Thanks, it's working now.

**Pull request merged**
